/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClienteRouteRouteImport } from './routes/cliente/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SuscripcionRouteImport } from './routes/suscripcion'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActividadRouteImport } from './routes/admin/actividad'
import { Route as AdminClientesRouteImport } from './routes/admin/clientes'
import { Route as AdminEntrenadoresRouteImport } from './routes/admin/entrenadores'
import { Route as AdminPlanesRouteImport } from './routes/admin/planes'
import { Route as AdminSuscripcionesRouteImport } from './routes/admin/suscripciones'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAjustesRouteImport } from './routes/app/ajustes'
import { Route as AppClasesRouteImport } from './routes/app/clases'
import { Route as AppEjerciciosRouteImport } from './routes/app/ejercicios'
import { Route as ClienteIndexRouteImport } from './routes/cliente/index'
import { Route as ClienteChatRouteImport } from './routes/cliente/chat'
import { Route as ClienteClasesRouteImport } from './routes/cliente/clases'
import { Route as ClienteEvaluacionesRouteImport } from './routes/cliente/evaluaciones'
import { Route as ClienteFotosRouteImport } from './routes/cliente/fotos'
import { Route as ClienteFuerzaRouteImport } from './routes/cliente/fuerza'
import { Route as ClienteHabitosRouteImport } from './routes/cliente/habitos'
import { Route as ClienteLogrosRouteImport } from './routes/cliente/logros'
import { Route as ClienteNutricionRouteImport } from './routes/cliente/nutricion'
import { Route as ClientePerfilRouteImport } from './routes/cliente/perfil'
import { Route as ClienteProgresoRouteImport } from './routes/cliente/progreso'
import { Route as ClienteRutinaRouteImport } from './routes/cliente/rutina'
import { Route as AppClientesIndexRouteImport } from './routes/app/clientes.index'
import { Route as AppClientesClientIdRouteImport } from './routes/app/clientes.$clientId'
import { Route as AppRutinasIndexRouteImport } from './routes/app/rutinas.index'
import { Route as AppRutinasRoutineIdRouteImport } from './routes/app/rutinas.$routineId'
import { Route as ClienteEntrenarDayIdRouteImport } from './routes/cliente/entrenar.$dayId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRouteRoute = ClienteRouteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SuscripcionRoute = SuscripcionRouteImport.update({
  id: '/suscripcion',
  path: '/suscripcion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActividadRoute = AdminActividadRouteImport.update({
  id: '/actividad',
  path: '/actividad',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEntrenadoresRoute = AdminEntrenadoresRouteImport.update({
  id: '/entrenadores',
  path: '/entrenadores',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlanesRoute = AdminPlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSuscripcionesRoute = AdminSuscripcionesRouteImport.update({
  id: '/suscripciones',
  path: '/suscripciones',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAjustesRoute = AppAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClasesRoute = AppClasesRouteImport.update({
  id: '/clases',
  path: '/clases',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEjerciciosRoute = AppEjerciciosRouteImport.update({
  id: '/ejercicios',
  path: '/ejercicios',
  getParentRoute: () => AppRouteRoute,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteRouteRoute,
} as any)
const ClienteChatRoute = ClienteChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ClienteRouteRoute,
} as any)
const ClienteClasesRoute = ClienteClasesRouteImport.update({
  id: '/clases',
  path: '/clases',
  getParentRoute: () => ClienteRouteRoute,
} as any)
const ClienteEvaluacionesRoute = ClienteEvaluacionesRouteImport.update({
  id: '/evaluaciones',
  path: '/evaluaciones',
  getParentRoute: () => ClienteRouteRoute,
} as any)
const ClienteFotosRoute = ClienteFotosRouteImport.update({
  id: '/fotos',
  path: '/fotos',
  getParentRoute: () => ClienteRouteRoute,
} as any)
const ClienteFuerzaRoute = ClienteFuerzaRouteImport.update({
  id: '/fuerza',
  path: '/fuerza',
  getParentRoute: () => ClienteRouteRoute,
} as any)
const ClienteHabitosRoute = ClienteHabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => ClienteRouteRoute,
} as any)
const ClienteLogrosRoute = ClienteLogrosRouteImport.update({
  id: '/logros',
  path: '/logros',
  getParentRoute: () => ClienteRouteRoute,
} as any)
const ClienteNutricionRoute = ClienteNutricionRouteImport.update({
  id: '/nutricion',
  path: '/nutricion',
  getParentRoute: () => ClienteRouteRoute,
} as any)
const ClientePerfilRoute = ClientePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ClienteRouteRoute,
} as any)
const ClienteProgresoRoute = ClienteProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => ClienteRouteRoute,
} as any)
const ClienteRutinaRoute = ClienteRutinaRouteImport.update({
  id: '/rutina',
  path: '/rutina',
  getParentRoute: () => ClienteRouteRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientesClientIdRoute = AppClientesClientIdRouteImport.update({
  id: '/clientes/$clientId',
  path: '/clientes/$clientId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRutinasIndexRoute = AppRutinasIndexRouteImport.update({
  id: '/rutinas/',
  path: '/rutinas/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRutinasRoutineIdRoute = AppRutinasRoutineIdRouteImport.update({
  id: '/rutinas/$routineId',
  path: '/rutinas/$routineId',
  getParentRoute: () => AppRouteRoute,
} as any)
const ClienteEntrenarDayIdRoute = ClienteEntrenarDayIdRouteImport.update({
  id: '/entrenar/$dayId',
  path: '/entrenar/$dayId',
  getParentRoute: () => ClienteRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/cliente': typeof ClienteRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suscripcion': typeof SuscripcionRoute
  '/admin/actividad': typeof AdminActividadRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/entrenadores': typeof AdminEntrenadoresRoute
  '/admin/planes': typeof AdminPlanesRoute
  '/admin/suscripciones': typeof AdminSuscripcionesRoute
  '/app/ajustes': typeof AppAjustesRoute
  '/app/clases': typeof AppClasesRoute
  '/app/ejercicios': typeof AppEjerciciosRoute
  '/cliente/chat': typeof ClienteChatRoute
  '/cliente/clases': typeof ClienteClasesRoute
  '/cliente/evaluaciones': typeof ClienteEvaluacionesRoute
  '/cliente/fotos': typeof ClienteFotosRoute
  '/cliente/fuerza': typeof ClienteFuerzaRoute
  '/cliente/habitos': typeof ClienteHabitosRoute
  '/cliente/logros': typeof ClienteLogrosRoute
  '/cliente/nutricion': typeof ClienteNutricionRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/progreso': typeof ClienteProgresoRoute
  '/cliente/rutina': typeof ClienteRutinaRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/app/clientes/$clientId': typeof AppClientesClientIdRoute
  '/app/rutinas/$routineId': typeof AppRutinasRoutineIdRoute
  '/cliente/entrenar/$dayId': typeof ClienteEntrenarDayIdRoute
  '/app/clientes/': typeof AppClientesIndexRoute
  '/app/rutinas/': typeof AppRutinasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suscripcion': typeof SuscripcionRoute
  '/admin/actividad': typeof AdminActividadRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/entrenadores': typeof AdminEntrenadoresRoute
  '/admin/planes': typeof AdminPlanesRoute
  '/admin/suscripciones': typeof AdminSuscripcionesRoute
  '/app/ajustes': typeof AppAjustesRoute
  '/app/clases': typeof AppClasesRoute
  '/app/ejercicios': typeof AppEjerciciosRoute
  '/cliente/chat': typeof ClienteChatRoute
  '/cliente/clases': typeof ClienteClasesRoute
  '/cliente/evaluaciones': typeof ClienteEvaluacionesRoute
  '/cliente/fotos': typeof ClienteFotosRoute
  '/cliente/fuerza': typeof ClienteFuerzaRoute
  '/cliente/habitos': typeof ClienteHabitosRoute
  '/cliente/logros': typeof ClienteLogrosRoute
  '/cliente/nutricion': typeof ClienteNutricionRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/progreso': typeof ClienteProgresoRoute
  '/cliente/rutina': typeof ClienteRutinaRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/cliente': typeof ClienteIndexRoute
  '/app/clientes/$clientId': typeof AppClientesClientIdRoute
  '/app/rutinas/$routineId': typeof AppRutinasRoutineIdRoute
  '/cliente/entrenar/$dayId': typeof ClienteEntrenarDayIdRoute
  '/app/clientes': typeof AppClientesIndexRoute
  '/app/rutinas': typeof AppRutinasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/cliente': typeof ClienteRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suscripcion': typeof SuscripcionRoute
  '/admin/actividad': typeof AdminActividadRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/entrenadores': typeof AdminEntrenadoresRoute
  '/admin/planes': typeof AdminPlanesRoute
  '/admin/suscripciones': typeof AdminSuscripcionesRoute
  '/app/ajustes': typeof AppAjustesRoute
  '/app/clases': typeof AppClasesRoute
  '/app/ejercicios': typeof AppEjerciciosRoute
  '/cliente/chat': typeof ClienteChatRoute
  '/cliente/clases': typeof ClienteClasesRoute
  '/cliente/evaluaciones': typeof ClienteEvaluacionesRoute
  '/cliente/fotos': typeof ClienteFotosRoute
  '/cliente/fuerza': typeof ClienteFuerzaRoute
  '/cliente/habitos': typeof ClienteHabitosRoute
  '/cliente/logros': typeof ClienteLogrosRoute
  '/cliente/nutricion': typeof ClienteNutricionRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/progreso': typeof ClienteProgresoRoute
  '/cliente/rutina': typeof ClienteRutinaRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/app/clientes/$clientId': typeof AppClientesClientIdRoute
  '/app/rutinas/$routineId': typeof AppRutinasRoutineIdRoute
  '/cliente/entrenar/$dayId': typeof ClienteEntrenarDayIdRoute
  '/app/clientes/': typeof AppClientesIndexRoute
  '/app/rutinas/': typeof AppRutinasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/cliente'
    | '/auth'
    | '/reset-password'
    | '/suscripcion'
    | '/admin/actividad'
    | '/admin/clientes'
    | '/admin/entrenadores'
    | '/admin/planes'
    | '/admin/suscripciones'
    | '/app/ajustes'
    | '/app/clases'
    | '/app/ejercicios'
    | '/cliente/chat'
    | '/cliente/clases'
    | '/cliente/evaluaciones'
    | '/cliente/fotos'
    | '/cliente/fuerza'
    | '/cliente/habitos'
    | '/cliente/logros'
    | '/cliente/nutricion'
    | '/cliente/perfil'
    | '/cliente/progreso'
    | '/cliente/rutina'
    | '/admin/'
    | '/app/'
    | '/cliente/'
    | '/app/clientes/$clientId'
    | '/app/rutinas/$routineId'
    | '/cliente/entrenar/$dayId'
    | '/app/clientes/'
    | '/app/rutinas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/suscripcion'
    | '/admin/actividad'
    | '/admin/clientes'
    | '/admin/entrenadores'
    | '/admin/planes'
    | '/admin/suscripciones'
    | '/app/ajustes'
    | '/app/clases'
    | '/app/ejercicios'
    | '/cliente/chat'
    | '/cliente/clases'
    | '/cliente/evaluaciones'
    | '/cliente/fotos'
    | '/cliente/fuerza'
    | '/cliente/habitos'
    | '/cliente/logros'
    | '/cliente/nutricion'
    | '/cliente/perfil'
    | '/cliente/progreso'
    | '/cliente/rutina'
    | '/admin'
    | '/app'
    | '/cliente'
    | '/app/clientes/$clientId'
    | '/app/rutinas/$routineId'
    | '/cliente/entrenar/$dayId'
    | '/app/clientes'
    | '/app/rutinas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/cliente'
    | '/auth'
    | '/reset-password'
    | '/suscripcion'
    | '/admin/actividad'
    | '/admin/clientes'
    | '/admin/entrenadores'
    | '/admin/planes'
    | '/admin/suscripciones'
    | '/app/ajustes'
    | '/app/clases'
    | '/app/ejercicios'
    | '/cliente/chat'
    | '/cliente/clases'
    | '/cliente/evaluaciones'
    | '/cliente/fotos'
    | '/cliente/fuerza'
    | '/cliente/habitos'
    | '/cliente/logros'
    | '/cliente/nutricion'
    | '/cliente/perfil'
    | '/cliente/progreso'
    | '/cliente/rutina'
    | '/admin/'
    | '/app/'
    | '/cliente/'
    | '/app/clientes/$clientId'
    | '/app/rutinas/$routineId'
    | '/cliente/entrenar/$dayId'
    | '/app/clientes/'
    | '/app/rutinas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ClienteRouteRoute: typeof ClienteRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuscripcionRoute: typeof SuscripcionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suscripcion': {
      id: '/suscripcion'
      path: '/suscripcion'
      fullPath: '/suscripcion'
      preLoaderRoute: typeof SuscripcionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/actividad': {
      id: '/admin/actividad'
      path: '/actividad'
      fullPath: '/admin/actividad'
      preLoaderRoute: typeof AdminActividadRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/entrenadores': {
      id: '/admin/entrenadores'
      path: '/entrenadores'
      fullPath: '/admin/entrenadores'
      preLoaderRoute: typeof AdminEntrenadoresRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/planes': {
      id: '/admin/planes'
      path: '/planes'
      fullPath: '/admin/planes'
      preLoaderRoute: typeof AdminPlanesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/suscripciones': {
      id: '/admin/suscripciones'
      path: '/suscripciones'
      fullPath: '/admin/suscripciones'
      preLoaderRoute: typeof AdminSuscripcionesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/ajustes': {
      id: '/app/ajustes'
      path: '/ajustes'
      fullPath: '/app/ajustes'
      preLoaderRoute: typeof AppAjustesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clases': {
      id: '/app/clases'
      path: '/clases'
      fullPath: '/app/clases'
      preLoaderRoute: typeof AppClasesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/ejercicios': {
      id: '/app/ejercicios'
      path: '/ejercicios'
      fullPath: '/app/ejercicios'
      preLoaderRoute: typeof AppEjerciciosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof ClienteRouteRoute
    }
    '/cliente/chat': {
      id: '/cliente/chat'
      path: '/chat'
      fullPath: '/cliente/chat'
      preLoaderRoute: typeof ClienteChatRouteImport
      parentRoute: typeof ClienteRouteRoute
    }
    '/cliente/clases': {
      id: '/cliente/clases'
      path: '/clases'
      fullPath: '/cliente/clases'
      preLoaderRoute: typeof ClienteClasesRouteImport
      parentRoute: typeof ClienteRouteRoute
    }
    '/cliente/evaluaciones': {
      id: '/cliente/evaluaciones'
      path: '/evaluaciones'
      fullPath: '/cliente/evaluaciones'
      preLoaderRoute: typeof ClienteEvaluacionesRouteImport
      parentRoute: typeof ClienteRouteRoute
    }
    '/cliente/fotos': {
      id: '/cliente/fotos'
      path: '/fotos'
      fullPath: '/cliente/fotos'
      preLoaderRoute: typeof ClienteFotosRouteImport
      parentRoute: typeof ClienteRouteRoute
    }
    '/cliente/fuerza': {
      id: '/cliente/fuerza'
      path: '/fuerza'
      fullPath: '/cliente/fuerza'
      preLoaderRoute: typeof ClienteFuerzaRouteImport
      parentRoute: typeof ClienteRouteRoute
    }
    '/cliente/habitos': {
      id: '/cliente/habitos'
      path: '/habitos'
      fullPath: '/cliente/habitos'
      preLoaderRoute: typeof ClienteHabitosRouteImport
      parentRoute: typeof ClienteRouteRoute
    }
    '/cliente/logros': {
      id: '/cliente/logros'
      path: '/logros'
      fullPath: '/cliente/logros'
      preLoaderRoute: typeof ClienteLogrosRouteImport
      parentRoute: typeof ClienteRouteRoute
    }
    '/cliente/nutricion': {
      id: '/cliente/nutricion'
      path: '/nutricion'
      fullPath: '/cliente/nutricion'
      preLoaderRoute: typeof ClienteNutricionRouteImport
      parentRoute: typeof ClienteRouteRoute
    }
    '/cliente/perfil': {
      id: '/cliente/perfil'
      path: '/perfil'
      fullPath: '/cliente/perfil'
      preLoaderRoute: typeof ClientePerfilRouteImport
      parentRoute: typeof ClienteRouteRoute
    }
    '/cliente/progreso': {
      id: '/cliente/progreso'
      path: '/progreso'
      fullPath: '/cliente/progreso'
      preLoaderRoute: typeof ClienteProgresoRouteImport
      parentRoute: typeof ClienteRouteRoute
    }
    '/cliente/rutina': {
      id: '/cliente/rutina'
      path: '/rutina'
      fullPath: '/cliente/rutina'
      preLoaderRoute: typeof ClienteRutinaRouteImport
      parentRoute: typeof ClienteRouteRoute
    }
    '/app/clientes/': {
      id: '/app/clientes/'
      path: '/clientes'
      fullPath: '/app/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clientes/$clientId': {
      id: '/app/clientes/$clientId'
      path: '/clientes/$clientId'
      fullPath: '/app/clientes/$clientId'
      preLoaderRoute: typeof AppClientesClientIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/rutinas/': {
      id: '/app/rutinas/'
      path: '/rutinas'
      fullPath: '/app/rutinas/'
      preLoaderRoute: typeof AppRutinasIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/rutinas/$routineId': {
      id: '/app/rutinas/$routineId'
      path: '/rutinas/$routineId'
      fullPath: '/app/rutinas/$routineId'
      preLoaderRoute: typeof AppRutinasRoutineIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/cliente/entrenar/$dayId': {
      id: '/cliente/entrenar/$dayId'
      path: '/entrenar/$dayId'
      fullPath: '/cliente/entrenar/$dayId'
      preLoaderRoute: typeof ClienteEntrenarDayIdRouteImport
      parentRoute: typeof ClienteRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminActividadRoute: typeof AdminActividadRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminEntrenadoresRoute: typeof AdminEntrenadoresRoute
  AdminPlanesRoute: typeof AdminPlanesRoute
  AdminSuscripcionesRoute: typeof AdminSuscripcionesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminActividadRoute: AdminActividadRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminEntrenadoresRoute: AdminEntrenadoresRoute,
  AdminPlanesRoute: AdminPlanesRoute,
  AdminSuscripcionesRoute: AdminSuscripcionesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAjustesRoute: typeof AppAjustesRoute
  AppClasesRoute: typeof AppClasesRoute
  AppEjerciciosRoute: typeof AppEjerciciosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientesClientIdRoute: typeof AppClientesClientIdRoute
  AppRutinasRoutineIdRoute: typeof AppRutinasRoutineIdRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppRutinasIndexRoute: typeof AppRutinasIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAjustesRoute: AppAjustesRoute,
  AppClasesRoute: AppClasesRoute,
  AppEjerciciosRoute: AppEjerciciosRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientesClientIdRoute: AppClientesClientIdRoute,
  AppRutinasRoutineIdRoute: AppRutinasRoutineIdRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppRutinasIndexRoute: AppRutinasIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ClienteRouteRouteChildren {
  ClienteChatRoute: typeof ClienteChatRoute
  ClienteClasesRoute: typeof ClienteClasesRoute
  ClienteEvaluacionesRoute: typeof ClienteEvaluacionesRoute
  ClienteFotosRoute: typeof ClienteFotosRoute
  ClienteFuerzaRoute: typeof ClienteFuerzaRoute
  ClienteHabitosRoute: typeof ClienteHabitosRoute
  ClienteLogrosRoute: typeof ClienteLogrosRoute
  ClienteNutricionRoute: typeof ClienteNutricionRoute
  ClientePerfilRoute: typeof ClientePerfilRoute
  ClienteProgresoRoute: typeof ClienteProgresoRoute
  ClienteRutinaRoute: typeof ClienteRutinaRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
  ClienteEntrenarDayIdRoute: typeof ClienteEntrenarDayIdRoute
}

const ClienteRouteRouteChildren: ClienteRouteRouteChildren = {
  ClienteChatRoute: ClienteChatRoute,
  ClienteClasesRoute: ClienteClasesRoute,
  ClienteEvaluacionesRoute: ClienteEvaluacionesRoute,
  ClienteFotosRoute: ClienteFotosRoute,
  ClienteFuerzaRoute: ClienteFuerzaRoute,
  ClienteHabitosRoute: ClienteHabitosRoute,
  ClienteLogrosRoute: ClienteLogrosRoute,
  ClienteNutricionRoute: ClienteNutricionRoute,
  ClientePerfilRoute: ClientePerfilRoute,
  ClienteProgresoRoute: ClienteProgresoRoute,
  ClienteRutinaRoute: ClienteRutinaRoute,
  ClienteIndexRoute: ClienteIndexRoute,
  ClienteEntrenarDayIdRoute: ClienteEntrenarDayIdRoute,
}

const ClienteRouteRouteWithChildren = ClienteRouteRoute._addFileChildren(
  ClienteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  ClienteRouteRoute: ClienteRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuscripcionRoute: SuscripcionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
